### ISSUE TITLE
Direction of b in the sketch

### ISSUE THREAD

**Issue by simonschmeisser** [Jmeyer1292/opw_kinematics#58]
We just had some great confusion party and smoking heads while trying to parametrize a Doosan robot due to the arrow in that graphics for b pointing in the wrong direction (?)

Here is an example back side view of a Stäubli TX2 90L robot:
![image](https://user-images.githubusercontent.com/372442/123818858-a0227080-d8f9-11eb-8cb8-8931b8a6a13b.png)

The parameters for the Stäubli that work perfectly fine and are consistent in the self-tests are
```
opw_kinematics_geometric_parameters:
    a1:  0.05
    a2:  0.0
    b:   0.050
    c1:  0.478
    c2:  0.500
    c3:  0.550
    c4:  0.100
opw_kinematics_joint_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
opw_kinematics_joint_sign_corrections: [1, 1, 1, 1, 1, 1]
```
as I also committed here ( https://github.com/ros-industrial/staubli_experimental/blob/kinetic-devel/staubli_tx2_90_support/config/opw_parameters_tx2_90l.yaml )

Comparing it with the sketch, `b` should be negative however.

@axelschroth
